apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: golang-app
spec:
  selector:
    app: go-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
